### ISSUE TITLE
nothing outputted

### ISSUE THREAD

**Issue by njzjz** [sphinx-contrib/scm#10]
I am wondering why nothing is outputted after I use the directive.

![image](https://user-images.githubusercontent.com/9496702/184046614-4ea0adf7-0976-48cf-8891-4b724383b45a.png)

```rst
Package Contributors
=========================

.. scm-sectionauthor::


Other Credits
=============
```

`'sphinxcontrib.scm'` has been added  to `extensions`.

**Comment by njzjz** [comment]
I see. I should set `show_authors` to `True`.

**Comment by lcnittl** [comment]
Glad you were able to find the problem!
