### ISSUE TITLE
the sphinxcontrib.scm extension does not declare if it is safe for parallel reading

### ISSUE THREAD

**Issue by prune998** [sphinx-contrib/scm#12]
I got this error when trying to build my docs in parallel mode using -j auto:

```
WARNING: the sphinxcontrib.scm extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

It seems pretty straightforward, but I don't know much about writing extensions: https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata

You can refer to what [email extension](https://github.com/sphinx-contrib/email/commit/a15b0b4e1ba4f0c19453179960c29e69f78cbb10) did

Thanks !

**Comment by lcnittl** [comment]
Sorry it took so long to fix this!

I declared it as safe for parallel reading, @prune998 please let me know if you run into any problems with that (in case you are still using this extension).
